### ISSUE TITLE
xlcutter: Parse Batches of 'xlsx' Files Based on a Template

### ISSUE THREAD

**Issue by Bisaloo** [ropensci/software-review#584]
Submitting Author Name: Hugo Gruson
Submitting Author Github Handle: @Bisaloo
Repository:  https://github.com/Bisaloo/xlcutter
Version submitted: 0.1.0
Submission type: Standard
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD
Language: en
---

-   Paste the full DESCRIPTION file inside a code block below:

```yaml
Package: xlcutter
Title: Parse Batches of 'xlsx' Files Based on a Template
Version: 0.1.0
Authors@R: 
    person(
      "Hugo", "Gruson", , "hugo.gruson+R@normalesup.org", 
      role = c("aut", "cre", "cph"),
      comment = c(ORCID = "0000-0002-4094-1476")
    )
Description: Parse entire folders of non-rectangular 'xlsx' files into a single
  rectangular and tidy 'data.frame' based on a custom template file defining the 
  column names of the output.
License: MIT + file LICENSE
Config/testthat/edition: 3
Encoding: UTF-8
Language: en-GB
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.2.3
Imports: 
    tidyxl
Suggests: 
    knitr,
    rmarkdown,
    testthat (>= 3.0.0)
VignetteBuilder: knitr
URL: https://github.com/Bisaloo/xlcutter, https://hugogruson.fr/xlcutter/
BugReports: https://github.com/Bisaloo/xlcutter/issues
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [x] data extraction
	- [x] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

This package provides a way to extract data from a large number of non-rectangular excel files based on a common template / format. It fills a gap in the software ecosystem, which usually focuses on already rectangular, or even tidy, data.

-   Who is the target audience and what are scientific applications of this package?

I expect this package to be of use in scientists, as well as non-scientist data users, in many areas. It is not linked to a specific domain area. It provides a generic way of parsing and importing a batch of excel (`.xlsx`) based on a user-defined template.
I have already used this package in a collaboration with a hospital who stored patient data in non-rectangular excel files. Colleagues from field epidemiology have also expressed that such a tool would be very useful as many of their collaborators produce this kind of non-rectangular files.
An important point is that this package explicitly aims at being usable by non-technical users because the template definition can be done in excel. But I believe it would also prove extremely useful to the most experienced R users, simplifying long custom parsing scripts into a single function call.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

I don't know of any other package accomplishing the same thing.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

Not applicable

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [ ] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [x] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.
